# Default values for helm-guestbook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

persistentVolume:
  name: navidrome-music-volume
  hostPath:
    path: "/home/user/server/music"

persistentVolumeClaim:
  name: navidrome-music-claim

deployment:
  name: navidrome-deployment
  appName: navidrome
  volume:
    name: navidrome-music

service:
  name: navidrome-service

replicaCount: 1

image:
  repository: deluan/navidrome
  tag: latest

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
