apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.Name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentVolume.hostPath.Path }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.PVCName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ .Values.persistentVolume.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      volumes:
        - name: navidrome-music
          persistentVolumeClaim:
            claimName: navidrome-music-claim
      containers:
        - name: {{ .Values.appName }}
          image: deluan/navidrome:latest
          ports:
            - containerPort: 4533
          env:
          - name: ND_SCANSCHEDULE
            value: 1h
          - name: ND_LOGLEVEL
            value: info
          - name: ND_SESSIONTIMEOUT
            value: 24h
          - name: ND_BASEURL
            value: ""
          volumeMounts:
            - mountPath: "/music:ro"
              name: navidrome-music
