apiVersion: v1
kind: Service
metadata:
  name: navidrome-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.appName }}
  ports:
    - protocol: TCP
      port: 4533
      targetPort: 4533
      nodePort: 30155